### PR TITLE
Work towards chrome install on travis

### PR DESCRIPTION
**Pull request by eriktrom**

### CODE REVIEW

**Comment by runspired** [comment]
I think you just need a rebase

**Comment by eriktrom** [comment]
@runspired - how far have u made it with installing chrome - exit code 100 - LOL - i followed this article real quick - any hints?

http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/

**Comment by runspired** [comment]
I think https://github.com/html-next/flexi/blob/master/.travis.yml is what we need to be doing

**Comment by runspired** [comment]
Odd, travis seems to hate this one

**Comment by runspired** [comment]
oh, PR this against master, I think I'm going to dump the whole `develop` workflow for this repo, it seemed to be confusing people too much.  The tests didn't build because this is against `develop` not master and in the PR it turns off develop from building lol

**Comment by eriktrom** [comment]
okay will go against master - good news - chrome installed - i think we should merge that on its own (since we know this is the setup required for that alone) - next failure is `The 'ember try:one' command requires a scenario specified in the config.` which is a different feature/checklist item - or no? ur call

**Comment by runspired** [comment]
In addition to moving against master, it appears the issue here is an incorrect ember-try config. I suspect that's been fixed on master.

**Comment by runspired** [comment]
@hbrysiewicz hi!!

**Comment by eriktrom** [comment]
this q is more important: we need new code climate code

`repo_token: 74740f388595590cab11e48b87581938d3596bf7718cd5df14ab90a8ab39e165` <-- from ur other repo, seems bad?

**Comment by runspired** [comment]
@eriktrom `dcdb6b3f5f69038c1e8ead30dd76ceb52fa93e000af9f07322132d03f5dc0530`

**Comment by eriktrom** [comment]
well this aint too bad:

image

will look into the one failure in the morning - 

regarding the commit line - sorry had a fight with git - it won - but the new squash button u see may fix it - things got ugly - and i almost got distracted during the fight -- but found my way back, phew :)

**Comment by runspired** [comment]
Going ahead and merging because I know how to fix the 1-13 test case already

**Pull request merged**
