### PR TITLE
add tests for all expected cases

### PR DESCRIPTION
**Pull request by eriktrom**
- fix error when not using loader 3.5.0 and jquery 1.11.3

WIP:

- input 'type' and 'value' cannot be added to a component, this requires
  a different approach for those elements
- 19/24 passing tests

### CODE REVIEW

**Comment by eriktrom** [comment]
I was curious so I wrote tests

they do not all pass yet - to be continued, not mergeable yet

**Comment by runspired** [comment]
I like the direction this is going but I'm too tired to grok all of the tests in play. Let's review on Friday.

**Comment by runspired** [comment]
Closing as this should now be opened against `develop`.

**Comment by eriktrom** [comment]
Sounds good.

**Pull request closed without merging**
